### ISSUE TITLE
Installation fails without any error message

### ISSUE THREAD

**Issue by FantasticNachos** [wishthis/wishthis#193]
## Branch
On which branch did you notice this bug?
- [x] stable
- [x] release-candidate
- [x] develop

## Description
Installation "seems" to work (config.php is being cretated with correct DB credentials, tables are created in DB). However, after install screen page stays empty without any error messages (index.php?page=install). Recalling URL just restarts installation. 

Have tired it with all branches.

## Disclaimer
wishthis is entirely built in my free time, mostly without any pay or code contributors. While I am doing my best to help out everybody, I cannot guarantee that I will find the time or have the competence to help you out.

I greatly appreciate that you are filing a bug report, these help tremendously! Thank you!

- [x] I understand that wishthis depends on volunteer work and that I am not entitled to any kind of support

**Comment by grandeljay** [comment]
Hey @FantasticNachos,

thanks for reporting this!

To get an idea what's happening here could you please answer the following questions (if you don't know the answer, please let me know and skip the question):
1. Are you using the docker image?
2. What kind of server software are you using? Apache or Nginx?
3. What is the PHP version set to?

**Comment by FantasticNachos** [comment]
Hi there,

>     1. Are you using the docker image?
**no**
>     2. What kind of server software are you using? Apache or Nginx?
 **Apache 2.4.38**
>     3. What is the PHP version set to?
**PHP 8.1**

**Comment by grandeljay** [comment]
That's very peculiar. It's difficult to guess what's wrong when the system is not yielding any information at all. Can you find something in your Apache error logs perhaps? Or could error reporting be disabled in your `php.ini`?

**Comment by grandeljay** [comment]
I'd also be interest what the Network tab in your browser's developer tools say. Does the installer return a HTTP 200 or is it rather a 404, 500, etc?

**Comment by FantasticNachos** [comment]
Hi,

the installer returns a HTTP 200 and with PHP error output the following message:

> Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes in /is/htdocs/webspace/www/wishthis/src/classes/wishthis/Database.php:65
Stack trace:
#0 /is/htdocs/webspace/www/wishthis/src/classes/wishthis/Database.php(65): PDOStatement->execute()
#1 /is/htdocs/webspace/www/wishthis/src/pages/install.php(330): wishthis\Database->query('CREATE TABLE `w...')
#2 /is/htdocs/webspace/www/wishthis/index.php(165): require('/is/htdocs/wp10...')
#3 {main} thrown in /is/htdocs/webspace/www/wishthis/src/classes/wishthis/Database.php on line 65

The following tables are created in the DB: users, wishlists. wishlists_saved

**Comment by grandeljay** [comment]
Ah interesting! The error seems to occur when the installer attempts to run this SQL command:
```sql
CREATE TABLE `wishes` (
    `id`             INT          NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `wishlist`       INT          NOT NULL,
    `title`          VARCHAR(128) NULL     DEFAULT NULL,
    `description`    TEXT         NULL     DEFAULT NULL,
    `image`          TEXT         NULL     DEFAULT NULL,
    `url`            VARCHAR(255) NULL     DEFAULT NULL,
    `priority`       TINYINT(1)   NULL     DEFAULT NULL,
    `status`         VARCHAR(32)  NULL     DEFAULT NULL,
    `is_purchasable` BOOLEAN      NOT NULL DEFAULT FALSE,
    `edited`         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    INDEX `idx_url` (`url`),
    CONSTRAINT `FK_wishes_wishlists` FOREIGN KEY (`wishlist`) REFERENCES `wishlists` (`id`) ON DELETE CASCADE
);
```
From what I could find out, this error typically occurs when you're trying to create an index on a column that exceeds the maximum key length of the database. The error message suggests that the key length is too long, which often happens when using a multi-column index or a column with a long data type, such as `VARCHAR`.

Would you mind trying if it works when you change the character limit to something higher? Like:
```sql
CREATE TABLE `wishes` (
    [...]
    `title`          VARCHAR(768) NULL DEFAULT NULL,
    [...]
    `url`            VARCHAR(768) NULL DEFAULT NULL,
    `priority`       TINYINT(1)   NULL DEFAULT NULL,
    `status`         VARCHAR(256) NULL DEFAULT NULL,
    [...]
);
```
It can be changed here:
https://github.com/wishthis/wishthis/blob/bddd16b8a8990f67f646599144f46a33fc353efd/src/pages/install.php#L325-L345

I'm just confused about why you are getting the error but I am not 🤔. What language is the UI for you? I wonder if it could be related to a particularly long translation string.

**Comment by FantasticNachos** [comment]
Hi, 
I am using the German version. 

Thanks for the proposed solution, will verify as soon as possible and come back here.

**Comment by FantasticNachos** [comment]
Hi, 

I have made the changes to install.php. It now looks like this:
```
           'CREATE TABLE `wishes` (
                `id`             INT          NOT NULL PRIMARY KEY AUTO_INCREMENT,
                `wishlist`       INT          NOT NULL,
                `title`          VARCHAR(768) NULL     DEFAULT NULL,
                `description`    TEXT         NULL     DEFAULT NULL,
                `image`          TEXT         NULL     DEFAULT NULL,
                `url`            VARCHAR(768) NULL     DEFAULT NULL,
                `priority`       TINYINT(1)   NULL     DEFAULT NULL,
                `status`         VARCHAR(256)  NULL     DEFAULT NULL,
                `is_purchasable` BOOLEAN      NOT NULL DEFAULT FALSE,
                `edited`         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                INDEX `idx_url` (`url`),
                CONSTRAINT `FK_wishes_wishlists` FOREIGN KEY (`wishlist`) REFERENCES `wishlists` (`id`) ON DELETE CASCADE
            );'
```

Unfortunatly I get the exact same error message:
```
Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes in /is/htdocs/webspace/www/wishthis/src/classes/wishthis/Database.php:65 Stack trace: #0 /is/htdocs/webspace/www/wishthis/src/classes/wishthis/Database.php(65): PDOStatement->execute() #1 /is/htdocs/webspace/www/wishthis/src/pages/install.php(330): wishthis\Database->query('CREATE TABLE `w...') #2 /is/htdocs/webspace/www/wishthis/index.php(138): require('/is/htdocs/wp10...') #3 {main} thrown in /is/htdocs/webspace/www/wishthis/src/classes/wishthis/Database.php on line 65
```
Again tried it with all branches and in both English and German...

**Comment by grandeljay** [comment]
Hmmm... What charset/collation is your database using? Can you please try `utf8mb4`?

**Comment by grandeljay** [comment]
What MySQL version are you using? Maybe I can reproduce the issue with your version.

**Comment by FantasticNachos** [comment]
MySQL version: 8.0.36-28
Charset/coallation: utf8mb4_0900_ai_ci

**Comment by grandeljay** [comment]
Unfortunately I am still not able to reproduce the issue. You could try removing the index so the installer can at least create the table and then you could try adding it later:

Remove this part
```sql
CREATE TABLE `wishes` (
    [...]
    INDEX `idx_url` (`url`),
    [...]
);
```

Run this manually after the installer completes:
```sql
CREATE INDEX `idx_url` ON `wishes` (`url`);
```

**Comment by FantasticNachos** [comment]
Thanks for trying to support once more, however it is still not working. Creating the index produces the following MySQL error: 

>#1071 - Specified key was too long; max key length is 1000 bytes

**Comment by grandeljay** [comment]
Is the installer otherwise running fine? Do you end up at a "Register" screen?

Leaving out the indexes will "only" lead to decreased performance. If you are hosting a small instance though, you may not notice the difference.

I'm not trying to dismiss the issue here but rather figure out how to get you up and running so I can take my time with this issue.

**Comment by FantasticNachos** [comment]
Sorry for the late reply.

No, I do not end up with the option to register. Same error as before on "index.php?page=install".

```
Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes in /is/htdocs/webspace/www/wishthis/src/classes/wishthis/Database.php:65 Stack trace: #0 /is/htdocs/webspace/www/wishthis/src/classes/wishthis/Database.php(65): PDOStatement->execute() #1 /is/htdocs/webspace/www/wishthis/src/pages/install.php(330): wishthis\Database->query('CREATE TABLE `w...') #2 /is/htdocs/webspace/www/wishthis/index.php(138): require('/is/htdocs/wp10...') #3 {main} thrown in /is/htdocs/webspace/www/wishthis/src/classes/wishthis/Database.php on line 65
```

**Comment by grandeljay** [comment]
I'm sorry, I have no idea what the issue could be. I can only think of a band-aid "solution" where you leave out the index as described in [my previous comment](https://github.com/wishthis/wishthis/issues/193#issuecomment-2041419869). Instead of adding it manually, I would just leave it out entirely.

Does that get you any further?

**Comment by FantasticNachos** [comment]
Hi, I tried leaving the index out before (it does not work) but I believe I did not post the error I receive after the installation has failed with the "key was too long" error and I recall the url:

`Fatal error: Uncaught ArgumentCountError: define() expects at least 2 arguments, 1 given in /is/htdocs/webspace/www/wishthis/src/config/config.php:19 Stack trace: #0 /is/htdocs/webspace/www/wishthis/src/config/config.php(19): define('********') #1 /is/htdocs/webspace/www/wishthis/index.php(42): require('/is/htdocs/wp10...') #2 {main} thrown in /is/htdocs/webspace/www/wishthis/src/config/config.php on line 19`

The "********" argument for define() is my DB password with the exception of the first character. I have tried different passwort lengths and it is always the same...first character is missing...

**Comment by grandeljay** [comment]
Ah neat, a different error! This one _should_ be an easy fix:

Please check your `config.php` and make sure the syntax/formatting is correct for your database password:
```php
define('DATABASE_PASSWORD', 'SuperSecretPassword');
```
According to the error, you didn't supply a password. Maybe the comma (`,`) is missing or something?

If your password contains apostrophes make sure to escape them properly: 
```php
define('DATABASE_PASSWORD', '!"§%$\'"/(=?');
```
Please note the `\'`. The backslash is ignored in this case, since it is used to escape the apostrophe.

**Comment by FantasticNachos** [comment]
Ok, we are getting somewhere. ;)

Just to list were we are now:

1. Installed with `INDEX 'idx_url' ('url'),` removed in install.php in line 342
2. Installation pushes me to `1071 Specified key was too long` error
3. I add `'DATABASE_PASSWORD',` and add first letter of my DB pswd to `define()` in line 19 and replace created config.php
4. I am able to view the Whisthis "Homepage" and can register a new user that is being created in user table in my DB

When trying to login with that newly created user I receive the following error message:


```php
Fatal error: Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'session' at row 1 in /is/htdocs/webspace/www/wishthis/src/classes/wishthis/Database.php:65 Stack trace: #0 /is/htdocs/webspace/www/wishthis/src/classes/wishthis/Database.php(65): PDOStatement->execute() #1 /is/htdocs/webspace/www/wishthis/src/classes/wishthis/User.php(642): wishthis\Database->query('INSERT INTO `se...', Array) #2 /is/htdocs/webspace/www/wishthis/src/classes/wishthis/User.php(414): wishthis\User->refreshSession(1) #3 /is/htdocs/webspace/www/wishthis/src/pages/login.php(21): wishthis\User->logIn('mail@example.o...', 'a10e8911099b53f...', false) #4 /is/htdocs/webspace/www/wishthis/index.php(138): require('/is/htdocs/websp...') #5 {main} thrown in /is/htdocs/webspace/www/wishthis/src/classes/wishthis/Database.php on line 65
```

**Comment by grandeljay** [comment]
Ok, sounds good! The error you have encountered now is a known bug (but no fix yet released, it's still on develop branch):

Try this please: https://github.com/wishthis/wishthis/commit/9d3e0cc16dea59f993803931e1e5b0f10b63ee70 (context: https://github.com/wishthis/wishthis/issues/192#issuecomment-1908107194) 😵‍💫

**Comment by FantasticNachos** [comment]
ok, got it working ...

not really same context but the sharing button does not work. Any ideas? (I want people to access the list without having to register)

**Comment by grandeljay** [comment]
> ok, got it working ...

Nice!

>  the sharing button does not work. Any ideas?

If you click the share button a link should be copied to your clipboard to give to anybody without an account. Does that not work for you?

**Comment by FantasticNachos** [comment]
`If you click the share button a link should be copied to your clipboard to give to anybody without an account. Does that not work for you?`

No it does not work (Edge, Firefox on both MacOS and Win10). However, I can rightclick and copy a link that works ...

(Also language is shown in German, but currency is always GDP)

**Comment by grandeljay** [comment]
> No it does not work (Edge, Firefox on both MacOS and Win10). However, I can rightclick and copy a link that works ...

I see. Glad you found a workaround!

> (Also language is shown in German, but currency is always GDP)

Check your preferences under profile. You can set the currency to something else, like EUR. It's also the default so I am surprised to read that it's GDP for you.

**Comment by grandeljay** [comment]
Is everything working for you now?

**Comment by Naeaeaeaeae** [comment]
I am not sure if its neccessary but my Problem was also a failed install. but i got the error message:

 Fatal error: Uncaught ArgumentCountError: define() expects at least 2 arguments, 1 given in /var/www/html/src/config/config.php:16 Stack trace: #0 /var/www/html/src/config/config.php(16): define('xx.yyy.zzz.3:93...') #1 /var/www/html/src/classes/wishthis/Config.php(21): require('/var/www/html/s...') #2 /var/www/html/index.php(41): wishthis\Config->load() #3 {main} thrown in /var/www/html/src/config/config.php on line 16
 
 And the problem was, that there was a missing "DATABASE_HOST" in the define argument AND the first number of the IP Adress was missing

**Comment by Naeaeaeaeae** [comment]
Today, i had the same error, but no time to investigate further:

Not found

The requested URL was not found on this server.
src/pages/aaaa.php

but the URL is: mydomain.com/wishlists/1?wishlist-name=Wunschsammlung_Naaaa

Maybe it helps

**Comment by grandeljay** [comment]
Hello @Naeaeaeaeae,

> The requested URL was not found on this server.
> src/pages/aaaa.php

how can I reproduce this error? The page `aaaa.php` does not exist in this project so it seems the error is appropriate in this case.

**Comment by Naeaeaeaeae** [comment]
My bad, i was creating a new wishlist and after i entered a name "Wunschsammlung_Naaaa", the website wanted to forward me to a the freshly created wishlist and the error message: URL was not found was shown. 

I think that equally to my installtion, where there were some signs missing in the first configuration data:
`'DATABASE_HOST', '1`

in this case wishthis was trying to access `.../aaaa.php` instead of `/Wunschsammlung_Naaaa.php`
in both cases were around 16 symbols missing and the pending operation was not completed.


The funny thing: today it worked, sry If I can somewhat provide more information, I will

**Comment by grandeljay** [comment]
Have you modified the `.htaccess` file? I tried creating a new wishlist but everything works as expected: 
![image](https://github.com/user-attachments/assets/aa45e7ce-fcb6-4d68-af3a-1b6c10ef388f)

Can you please share your complete `.htaccess` and `config.php` file? Just make sure to replace sensitive information with placeholders.

**Comment by Naeaeaeaeae** [comment]
AS I said, i am not sure why it didnt work and not it works. I use Truenas SCALE Dragonfish-24.04.2 with a custom app -> Docker https://hub.docker.com/r/hiob/wishthis and MariaDB as Database

config.php
[config.txt](https://github.com/user-attachments/files/16814867/config.txt)
.htaccess
[htaccess.txt](https://github.com/user-attachments/files/16814873/htaccess.txt)


I did not modify any files inside the Docker (apart from the config.php)

**Comment by grandeljay** [comment]
Thanks, everything looks fine here. How does your PHP error log look? Is there anything inside it?
