### ISSUE TITLE
Typo on MJML settings page :  API key is requested instead of the Application ID

### ISSUE THREAD

**Issue by Hiobi** [wishthis/wishthis#47]
Hi,

I think there is a little typo on MJML settings page.
On [MJML documentation](https://mjml.io/api/documentation/) it's appears that `APPLICATION-ID`  and `SECRET-KEY` are required for when calling the MJML API from a web browser.

But on Wishthis's MJML settings page, placeholders ask for `Key` and `Secret` : 
- if I filled `key` with my API key, I've got the error below. 
- If I filled with my `Application ID` it's work.

Oh ! The HTML selector should be renamed too `<input type="text" name="api_key">`

thanks !

```PHP
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://api.mjml.io/v1/render` resulted in a `401 Unauthorized` response: {"message":"Authentication required","request_id":"123123123133","started_at":"2022-11-09T11:04: (truncated...) in /var/www/html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL) #1 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL) #3 /var/www/html/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run(true) #5 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn() #6 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending() #7 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList() #8 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #9 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Promise\Promise->wait() #10 /var/www/html/vendor/guzzlehttp/guzzle/src/ClientTrait.php(95): GuzzleHttp\Client->request('POST', 'render', Array) #11 /var/www/html/vendor/qferr/mjml-php/src/Mjml/Renderer/ApiRenderer.php(61): GuzzleHttp\Client->post('render', Array) #12 /var/www/html/src/classes/email.php(66): Qferrer\Mjml\Renderer\ApiRenderer->render('<mjml lang="fr_...') #13 /var/www/html/src/api/wishlists.php(78): wishthis\Email->send() #14 {main} thrown in /var/www/html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
```
![wishthis_MJML_settings](https://user-images.githubusercontent.com/2171856/200815094-ede25544-87d6-4b9b-b404-92c1cab2d6c1.png)

**Comment by grandeljay** [comment]
Alrighty, version 0.7.1 should fix this. Let me know if you are still having issues, closing this for now.
