### ISSUE TITLE
Fatal error: Uncaught TypeError: hash_file(): Argument #2 ($filename) must be of type string

### ISSUE THREAD

**Issue by Hiobi** [wishthis/wishthis#57]
Hi @grandeljay ,
On very latest develop branch commit, docker image built at _déc. 1, 2022 11:51pm GMT+0100_ ([latest commit](https://github.com/grandeljay/wishthis/commit/b01d2933e30e7e4ef9aded16175e93d174f72bb8)), when login I got the following error:

```PHP

Fatal error: Uncaught TypeError: hash_file(): Argument #2 ($filename) must be of type string, array given in /var/www/html/src/classes/page.php:312 Stack trace: #0 /var/www/html/src/classes/page.php(312): hash_file('crc32', Array) #1 /var/www/html/src/pages/home.php(12): wishthis\Page->header() #2 /var/www/html/index.php(163): require('/var/www/html/s...') #3 {main} thrown in /var/www/html/src/classes/page.php on line 312

```

Thanks !

**Comment by grandeljay** [comment]
Thanks for reporting this!

Should be working now 👍🏼
